name: Update News Headlines

on:
  schedule:
    - cron: '0 12 * * *' # Runs every day at 12:00 UTC (8am ET)
  workflow_dispatch:      # Also lets you run it manually from GitHub

jobs:
  update-news:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Run news script
        env:
          NEWS_API_KEY: ${{ secrets.NEWS_API_KEY }}
        run: node index.js

      - name: Commit updated news.json
        run: |
          git config user.name "vilaj-bot"
          git config user.email "bot@vilaj.io"
          git add public/news.json
          git commit -m "🔁 Auto-update news.json [GitHub Action]" || echo "No changes"
          git push

      - name: Commit updated news.json
        run: |
          git config user.name "vilaj-bot"
          git config user.email "bot@vilaj.io"
          git add public/news.json
          git diff --cached --quiet || git commit -m "Auto-update news.json"
          git push

